### PR TITLE
feat: disable bloom fliter by default

### PR DESCRIPTION
**Pull request by ZENOTME**
As in https://github.com/risingwavelabs/risingwave/issues/13048#issuecomment-1780572388, enable bloom fliter may cause huge memory cost. So let's disable by default.

### CODE REVIEW

**Review by liurenjie1024 — APPROVED** [review]

**Comment by ZENOTME** [comment]
arrow-* 48 introduce some breaking change. I'm concertn with whether is appropriate for settting version as `>=48`. E.g. arrow 49 may introduce breaking change. Maybe we need to limit the upper bound and lower bound.(set 48 for now)

**Comment by liurenjie1024** [comment]
+1 Arrow's major version upgrade doesn't ensure backward compatibility CC @Xuanwo How do you think.

**Comment by Xuanwo** [comment]
> +1 Arrow's major version upgrade doesn't ensure backward compatibility CC @Xuanwo How do you think.

Indeed, but we can't provide any assistance. All we can do is ensure it's compilable. Users of icelake may depend on differnet arrow versions. And it's hard to bump arrow version for them since it's a huge changes (unlike `opendal`).

**Comment by liurenjie1024** [comment]
> > +1 Arrow's major version upgrade doesn't ensure backward compatibility CC @Xuanwo How do you think.
> 
> Indeed, but we can't provide any assistance. All we can do is ensure it's compilable. Users of icelake may depend on differnet arrow versions. And it's hard to bump arrow version for them since it's a huge changes (unlike the case for `opendal` which we, at least me, knows what changed).

I'm thinking about using fixed version of arrow. But it should block this pr, let's discuss it in another thread.

**Pull request merged**
