### PR TITLE
chore: allow depending on arrow and parquet v46

### PR DESCRIPTION
**Pull request by wangrunji0408**
regular dependency updates

### CODE REVIEW

**Review by Xuanwo — APPROVED** [review]
Thanks! Would you like to help fix the CI?

**Comment by wangrunji0408** [comment]
CI test failed on the last commit. Is this all right?

**Comment by Xuanwo** [comment]
Oh, sorry for merging so quick. I don't know why https://github.com/icelake-io/icelake/pull/162/commits/ba42b7fb9ba360d8d1ca2bc2b356accfe3de147f breaks our unit test.

**Comment by Xuanwo** [comment]
> Oh, sorry for merging so quick. I don't know why [ba42b7f](https://github.com/icelake-io/icelake/commit/ba42b7fb9ba360d8d1ca2bc2b356accfe3de147f) breaks our unit test.

cc @liurenjie1024 @ZENOTME, this test case seems flaky

**Comment by liurenjie1024** [comment]
> > Oh, sorry for merging so quick. I don't know why [ba42b7f](https://github.com/icelake-io/icelake/commit/ba42b7fb9ba360d8d1ca2bc2b356accfe3de147f) breaks our unit test.
> 
> cc @liurenjie1024 @ZENOTME, this test case seems flaky

I'll take a look

**Pull request merged**
