### PR TITLE
feat: add base_writer in io_v2

### PR DESCRIPTION
**Pull request by ZENOTME**
This PR adds base writer in io_v2:
1. DataFileWriter
2. PositionDeleteWriter
3. EqualityDeleteWriter
4. SortWriter 

They are the writer which writes in a single partition.

### CODE REVIEW

**Review by liurenjie1024 — COMMENTED** [review]
Generally LGTM. I think one thing worth discussion is that for writers in this layer, do we need put them in `IcebergWriter` trait? It's worth to put `AppendOnlyWriter`/`UpserWriter` under that layer since they can be reused to combine with partitioner. For writers in this layer, when they are used, they are always used with concrete class, what's the benefit of putting them under same trait?

**Comment by ZENOTME** [comment]
> Generally LGTM. I think one thing worth discussion is that for writers in this layer, do we need put them in IcebergWriter trait? It's worth to put AppendOnlyWriter/UpserWriter under that layer since they can be reused to combine with partitioner. For writers in this layer, when they are used, they are always used with concrete class, what's the benefit of putting them under same trait?

In the new writer, actually we don't have `AppendOnlyWriter` and `UpserWriter`. 
- The `DataFileWriter` is the AppendOnlyWriter. (That's why it need to implement the `IcebergWriter` trait). 
- The `EqualityDeltaWriter` is `UpsertWriter`. 

Put them under same trait will give user more flexibilty: 
1.  EqualityDeltaWriter is not use concrete class for them, actually it look like:
```
struct EqualityDeltaWriter<A:IcebergWriter,B:IcebergWriter,C:IcebergWriter> {
  data_file_writer: A,
  position_delete_writer: B,
  equlity_delete_writer: C
}
```
So that user can custom the inner writer, e.g., they want to collect writer performance metric of data file writer. 

2. User may want to use them directly, so that they also can combine them with ParitionWriter or other functional writer like DataFileWriter.

**Comment by liurenjie1024** [comment]
> > Generally LGTM. I think one thing worth discussion is that for writers in this layer, do we need put them in IcebergWriter trait? It's worth to put AppendOnlyWriter/UpserWriter under that layer since they can be reused to combine with partitioner. For writers in this layer, when they are used, they are always used with concrete class, what's the benefit of putting them under same trait?
> 
> In the new writer, actually we don't have `AppendOnlyWriter` and `UpserWriter`.
> 
> * The `DataFileWriter` is the unpartition AppendOnlyWriter. (That's why it need to implement the `IcebergWriter` trait).
> * The `EqualityDeltaWriter` is unpartition `UpsertWriter`.
> 
> Put them under same trait will give user more flexibilty:
> 
> 1. EqualityDeltaWriter don't use concrete class for them, actually it look like:
> 
> ```
> struct EqualityDeltaWriter<A:IcebergWriter,B:IcebergWriter,C:IcebergWriter> {
>   data_file_writer: A,
>   position_delete_writer: B,
>   equlity_delete_writer: C
> }
> ```
> 
> So that user can custom the inner writer, e.g., they want to collect writer performance metric of data file writer.
> 
> 2. User may want to use them directly, so that they also can combine them with ParitionWriter or other functional writer like DataFileWriter.

Sounds reasonable.

**Review by liurenjie1024 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
